name: ProfilesRpg
version: '${project.version}'
main: hillwalk.fr.profilesrpg.ProfilesRpg
api-version: 1.16

softdepend:
  - LuckPerms
  - MMOCore

commands:
  profile:
    description: Main command for the ProfilesRPG plugin.
    usage: /<command> [subcommand] [args]
    aliases: [pr, profilerpg]